#!/bin/bash

from flask import Flask,request

server=Flask(__name__)
token="5350892952:AAF_W75KZPR3lf1CpSm1dwCcaBw4dFpXDlE"

bot=telebot.TeleBot(token)
_get_ziplink () {
    local regex
    regex='(https?)://github.com/.+/.+'
    if [[ $UPSTREAM_REPO == "jmthonrz" ]]
    then
        echo "aHR0cHM6Ly9naXRodWIuY29tL2ptdGhvbmFyL3VzZXJib3QvYXJjaGl2ZS9tYXN0ZXIuemlw==" | base64 -d
    elif [[ $UPSTREAM_REPO =~ $regex ]]
    then
        if [[ $UPSTREAM_REPO_BRANCH ]]
        then
            echo "${UPSTREAM_REPO}/archive/${UPSTREAM_REPO_BRANCH}.zip"
        else
            echo "${UPSTREAM_REPO}/archive/master.zip"
        fi
    else
        echo "aHR0cHM6Ly9naXRodWIuY29tL2ptdGhvbmFyL3VzZXJib3QvYXJjaGl2ZS9tYXN0ZXIuemlw==" | base64 -d
    fi
}

_get_repolink () {
    local regex
    local rlink
    regex='(https?)://github.com/.+/.+'
    if [[ $UPSTREAM_REPO == "jmthonrz" ]]
    then
        rlink=`echo "aHR0cHM6Ly9naXRodWIuY29tL2ptdGhvbmFyL3VzZXJib3QuZ2l0" | base64 -d`
    elif [[ $UPSTREAM_REPO =~ $regex ]]
    then
        rlink=`echo "${UPSTREAM_REPO}"`
    else
        rlink=`echo "aHR0cHM6Ly9naXRodWIuY29tL2ptdGhvbmFyL3VzZXJib3QuZ2l0" | base64 -d`
    fi
    echo "$rlink"
}


_run_python_code() {
    python3${pVer%.*} -c "$1"
}

_run_catpack_git() {
    $(_run_python_code 'from git import Repo
import sys
OFFICIAL_UPSTREAM_REPO = "https://github.com/jmthonar/userbot"
ACTIVE_BRANCH_NAME = "master"
repo = Repo.init()
origin = repo.create_remote("temponame", OFFICIAL_UPSTREAM_REPO)
origin.fetch()
repo.create_head(ACTIVE_BRANCH_NAME, origin.refs[ACTIVE_BRANCH_NAME])
repo.heads[ACTIVE_BRANCH_NAME].checkout(True) ')
}

_run_cat_git() {
    local repolink=$(_get_repolink)
    $(_run_python_code 'from git import Repo
import sys
OFFICIAL_UPSTREAM_REPO="'$repolink'"
ACTIVE_BRANCH_NAME = "'$UPSTREAM_REPO_BRANCH'" or "master"
repo = Repo.init()
origin = repo.create_remote("temponame", OFFICIAL_UPSTREAM_REPO)
origin.fetch()
repo.create_head(ACTIVE_BRANCH_NAME, origin.refs[ACTIVE_BRANCH_NAME])
repo.heads[ACTIVE_BRANCH_NAME].checkout(True) ')
}

_set_bot () {
    local zippath
    zippath="userbot.zip"
    echo "جاري تنزيل اكواد السورس "
    wget -q $(_get_ziplink) -O "$zippath"
    echo " تفريغ البيانات "
    CATPATH=$(zipinfo -1 "$zippath" | grep -v "/.");
    unzip -qq "$zippath"
    echo " تم التفريغ "
    echo " يتم التنظيف "
    rm -rf "$zippath"
    sleep 5
    _run_catpack_git
    cd $CATPATH
    _run_cat_git
    python3 ../setup/updater.py ../requirements.txt requirements.txt
    chmod -R 755 bin
    echo "    جار بدء جمثون    "
    echo "

    "
    python3 -m userbot
}
@server.route("/"+token,methods=["POST"])

def getMessage():

    bot.process_new_updates([telebot.types.Update.de_json(request.stream.read().decode("utf-8"))])

    return "!",200

@server.route("/")

def webhook():

    bot.remove_webhook()

    bot.set_webhook(url="رابط استضافتك"+token)

    return "!",200

server.run(host="0.0.0.0",port=int(os.environ.get("PORT",5000)))
